### PR TITLE
remove '--version' from 'helm repo add'

### PR DESCRIPTION
**Pull request by westongcooper**
--version is not part of `helm repo add`
https://helm.sh/docs/helm/helm_repo_add/

### CODE REVIEW

**Comment by westongcooper** [comment]
@nicks @landism can you look at this bug fix?

**Comment by KOGI** [comment]
This bug was introduced with #50

**Comment by KOGI** [comment]
FYI @Tchoupinax

**Comment by Tchoupinax** [comment]
Thanks ! @KOGI

**Pull request merged**
