### PR TITLE
helm_resource: add namespace to kubectl command

### PR DESCRIPTION
**Pull request by markmixson**
Signed-off-by: Mark Mixson <mixson_mark@bah.com>

### CODE REVIEW

**Comment by markmixson** [comment]
```
   helloworld │      error: the namespace from the provided object "kube-public" does not match the namespace "app". You must pass '--namespace=kube-public' to perform this operation.
```
Not understanding how "kube-public" is involved here.

**Comment by markmixson** [comment]
references #435

**Comment by nicks** [comment]
you're not the first person who has made this mistake, that's why we have tests for it :sweat_smile: 

kubectl namespace defaulting and helm namespace defaulting have different semantics. Even though the flags are both called `--namespace`, they do different things.

**Comment by markmixson** [comment]
I'm trying to fix something that is broken.  Based on #435 I had to do this to get the helm chart to work in Windows 🤷

**Comment by markmixson** [comment]
Apparently there's bigger problems than this in Windows. . . .

**Pull request closed without merging**
