### PR TITLE
helm_resource: add a test for charts with multiple namespaces

### PR DESCRIPTION
**Pull request by nicks**
Hello @nicksieger,

Please review the following commits I made in branch nicks/namespace-semantics:

61f98c54b6af50bf500893108c07bfadc76f334e (2022-06-27 18:15:49 -0400)
helm_resource: add a test for charts with multiple namespaces

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
sorry, should have added a test for this in the first place, because the semantics are really subtle. This would have caught the bug in the other PR.

**Comment by nicksieger** [comment]
Thanks for this. Yeah, I pulled the PR and ran the test locally before merging. And the test workflow didn't get triggered on the other PR, is that because of a first-time or outside contributor?

**Review by nicksieger — APPROVED** [review]

**Comment by nicks** [comment]
eh, we should have had a test for it anyway, i meant to add one but must have forgotten.

**Comment by nicks** [comment]
sent you a separate pr for the outside contributor ci

**Pull request merged**
