### PR TITLE
helm_remote - fix grep command for mac

### PR DESCRIPTION
**Pull request by KOGI**
@nicks #38

### CODE REVIEW

**Comment by KOGI** [comment]
@nicks I'm not a huge fan of resorting to platform detection for this, so I'm all ears if you've got better idea(s)

**Comment by nicks** [comment]
hmmmm...doesn't the exit code problem also exist on mac though?

**Comment by KOGI** [comment]
xargs on mac always runs with an implicit `-r` (which is why it's not an option on mac)

**Comment by nicks** [comment]
ah ok. lgtm!

**Pull request merged**
