### PR TITLE
add helm_remote_yaml

### PR DESCRIPTION
**Pull request by sethpollack**
Adds `helm_remote_yaml`

Example use case would be generating the yaml with helm and then applying some transformations before installing.

### CODE REVIEW

**Comment by nicks** [comment]
for other extensions, the API pattern we've used is to break this into two separate functions -- e.g., deployment_create and deployment_yaml - https://github.com/tilt-dev/tilt-extensions/tree/master/deployment

could we do the same thing here? so this would become helm_remote_yaml?

**Comment by sethpollack** [comment]
Works for me. Just to be clear, add a new extension `helm_remote_yaml` and then update `helm_remote` to use `helm_remote_yaml` and call `k8s_yaml` with the output, right?

**Comment by sethpollack** [comment]
@nicks Let me know if this is what you had in mind?

**Review by nicks — APPROVED** [review]
nice!

**Comment by sethpollack** [comment]
Thanks!

**Pull request merged**
