### PR TITLE
feat(ngrok): Ngrok extension to support V3

### PR DESCRIPTION
**Pull request by adinhodovic**
https://ngrok.com/docs/guides/upgrade-v2-v3

Do I need to add compability for Ngrok v2 agent (v1 config)?

Also added a flag for specifying default_ngrok_config.

### CODE REVIEW

**Comment by nicks** [comment]
ya, i think we probably need a way for people to transition? i'd be fine with a `version` param, and use the old config on version 2

**Comment by adinhodovic** [comment]
> ya, i think we probably need a way for people to transition? i'd be fine with a `version` param, and use the old config on version 2

Would that work?

**Comment by JakulaTechuniverse** [comment]
Can someone please help me install ngrok agent v3 ?

**Comment by JakulaTechuniverse** [comment]
I managed . I guess they no longer support phishing . Coz i was trying to demonstrate phishing with blackeye to my students and they blocked me . I guess i'll have to find another ngrok alternative for phishing .

**Pull request merged**
