### PR TITLE
honeycomb: support custom_build

### PR DESCRIPTION
**Pull request by jazzdan**
Ends up looking something like this:

Screen Shot 2022-01-10 at 9 47 54 PM

### CODE REVIEW

**Comment by jazzdan** [comment]
Looks like the tests aren't running against the latest Tilt?

**Comment by nicks** [comment]
ya - we have to bump the version manually. tho i think you'll still need a try...catch block so that this doesn't break older users (i think CmdImage was added VERY recently, like the last release or two)

**Comment by nicks** [comment]
added some tests and sent out https://github.com/tilt-dev/tilt-extensions/pull/329

**Comment by jazzdan** [comment]
Whoops, thanks for running with this @nicks! It got lost in the shuffle of moving.

**Comment by nicks** [comment]
superseded by https://github.com/tilt-dev/tilt-extensions/pull/329 !

**Pull request closed without merging**
